name: fab_circular_menu_example
version: 1.0.0+1
description: FAB Circular Menu Example
environment: 
  sdk: '>=2.15.0 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.4
  flutter: 
    sdk: flutter
  fab_circular_menu: 
    hosted: https://dart.cloudsmith.io/edspuzzles/edspuzzle-public/
    version: ^1.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
